<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Vilens</RootNamespace>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
    <IsPackable>false</IsPackable>
    <PublishAot Condition="'$(Aot)' != ''">true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vilens\Vilens.csproj" />
  </ItemGroup>

</Project>
