name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number to release"
        required: true
        type: string
      push:
        description: "Push to nuget.org"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: ⤵️ Checkout Source
      uses: actions/checkout@v6

    - name: 🛠️ Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: 🛠️ Restore dependencies
      run: dotnet restore

    - name: 📦 Pack
      run: dotnet pack --no-restore --property:Version=${{ inputs.version }} --output ./publish --configuration Release

    - uses: actions/upload-artifact@v7
      name: 🚀 Upload
      with:
        name: nuget
        path: ./publish
        if-no-files-found: error

    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: PhilippNaused

    - name: 🚀 Push
      if: ${{ inputs.push }}
      run: dotnet nuget push ./publish/* --skip-duplicate --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
